-- EarTrain learning profiles, scoring history, and cross-app identity groundwork.
-- Instructors authenticate through Supabase Auth. Students are separate records:
-- a future Edge Function will exchange a short-lived reading.oclef.com launch
-- token for a student-scoped session. Never expose service-role credentials or
-- allow anonymous clients to select student_access_grants directly.

create extension if not exists pgcrypto;

create table if not exists public.student_profiles (
  id uuid primary key default gen_random_uuid(),
  instructor_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 120),
  status text not null default 'active' check (status in ('active', 'paused', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists student_profiles_instructor_idx
  on public.student_profiles (instructor_id, status);

create table if not exists public.student_external_identities (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.student_profiles(id) on delete cascade,
  provider text not null check (provider in ('eartrain', 'reading.oclef.com')),
  external_subject text not null,
  linked_at timestamptz not null default now(),
  unique (provider, external_subject),
  unique (student_id, provider)
);

create table if not exists public.practice_sessions (
  id uuid primary key,
  student_id uuid not null references public.student_profiles(id) on delete cascade,
  source_app text not null check (source_app in ('eartrain-web', 'reading.oclef.com')),
  installation_id text not null,
  started_at timestamptz not null,
  last_activity_at timestamptz not null,
  ended_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists practice_sessions_student_time_idx
  on public.practice_sessions (student_id, started_at desc);

-- event_id is generated by the client and is the idempotency key. Replaying an
-- offline batch is an UPSERT, so retries cannot double-award progress or credit.
create table if not exists public.exercise_attempts (
  event_id text primary key,
  schema_version integer not null,
  student_id uuid not null references public.student_profiles(id) on delete cascade,
  session_id uuid not null references public.practice_sessions(id) on delete cascade,
  installation_id text not null,
  occurred_at timestamptz not null,
  curriculum_id text not null,
  curriculum_version text not null,
  concept_id text not null,
  concept_index integer not null,
  question_id text not null,
  question_number integer not null,
  attempt_number integer not null,
  exercise_mode text,
  difficulty double precision not null check (difficulty between 0 and 1),
  passed boolean not null,
  pitch_score double precision not null check (pitch_score between 0 and 5),
  timing_score double precision check (timing_score between 0 and 5),
  cleanliness_score double precision not null check (cleanliness_score between 0 and 5),
  overall_score double precision not null check (overall_score between 0 and 5),
  position_key text not null,
  duration_accuracy double precision check (duration_accuracy between 0 and 1),
  payload jsonb not null,
  received_at timestamptz not null default now()
);

create index if not exists exercise_attempts_student_time_idx
  on public.exercise_attempts (student_id, occurred_at desc);
create index if not exists exercise_attempts_student_concept_idx
  on public.exercise_attempts (student_id, concept_id, difficulty);
create index if not exists exercise_attempts_payload_gin_idx
  on public.exercise_attempts using gin (payload);

create table if not exists public.student_learning_checkpoints (
  student_id uuid not null references public.student_profiles(id) on delete cascade,
  curriculum_id text not null,
  curriculum_version text not null,
  lesson_index integer not null,
  question_number integer not null,
  difficulty double precision not null check (difficulty between 0 and 1),
  last_attempt_id text references public.exercise_attempts(event_id) on delete set null,
  adaptive_profile jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null,
  primary key (student_id, curriculum_id)
);

-- Only a trusted server/Edge Function can inspect or redeem these hashes.
-- Store SHA-256(token), never the raw bearer token from the redirect URL.
create table if not exists public.student_access_grants (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.student_profiles(id) on delete cascade,
  token_hash bytea not null unique,
  created_by uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null,
  redeemed_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.student_profiles enable row level security;
alter table public.student_external_identities enable row level security;
alter table public.practice_sessions enable row level security;
alter table public.exercise_attempts enable row level security;
alter table public.student_learning_checkpoints enable row level security;
alter table public.student_access_grants enable row level security;

create policy "instructors manage their students"
  on public.student_profiles for all
  using (instructor_id = auth.uid())
  with check (instructor_id = auth.uid());

create policy "instructors manage student identity links"
  on public.student_external_identities for all
  using (exists (
    select 1 from public.student_profiles s
    where s.id = student_id and s.instructor_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.student_profiles s
    where s.id = student_id and s.instructor_id = auth.uid()
  ));

create policy "instructors read their student sessions"
  on public.practice_sessions for select
  using (exists (
    select 1 from public.student_profiles s
    where s.id = student_id and s.instructor_id = auth.uid()
  ));

create policy "instructors read their student attempts"
  on public.exercise_attempts for select
  using (exists (
    select 1 from public.student_profiles s
    where s.id = student_id and s.instructor_id = auth.uid()
  ));

create policy "instructors read their student checkpoints"
  on public.student_learning_checkpoints for select
  using (exists (
    select 1 from public.student_profiles s
    where s.id = student_id and s.instructor_id = auth.uid()
  ));

-- No anon/authenticated policies are created for access grants or student
-- writes. A token-exchange Edge Function validates the grant using service-role
-- access, then performs idempotent attempt/checkpoint upserts on that student's
-- behalf. This is the security boundary needed for passwordless students.
